"use client";
import { useState, useEffect, Fragment } from "react";
import { useRouter } from "next/navigation";
import { SCHEDULE_POLAS, SCHEDULE_FLAGS } from "@/lib/schedules/pola";
import { exportScheduleMatrixExcel } from "@/lib/schedules/exportExcel";
import { departmentColor } from "@/lib/schedules/deptColors";
import { shiftCellColor, SHIFT_COLOR_LEGEND } from "@/lib/schedules/shiftColors";
import { toDateOnlyString } from "@/lib/schedules/dates";
import { HIGHLIGHT_COLORS } from "@/lib/schedules/access";
import { buildDeptSummaries, isWorkingShiftName } from "@/lib/schedules/fairness";

export default function SchedulesClient({
  initialShiftTypes,
  users: initialUsers,
  locations,
  departments: initialDepartments = [],
  currentUser,
  scheduleConfig = {},
  canEdit = false,
  canEngine = false,
}) {
  const router = useRouter();
  const [activeTab, setActiveTab] = useState("calendar");
  const [shiftTypes, setShiftTypes] = useState(initialShiftTypes);
  const [users, setUsers] = useState(initialUsers);
  const [departments, setDepartments] = useState(initialDepartments);

  const isEditor = !!canEdit;
  const isScheduleAdmin = !!canEngine;

  const [schedules, setSchedules] = useState([]);
  const [calMonth, setCalMonth] = useState(new Date().getMonth());
  const [calYear, setCalYear] = useState(new Date().getFullYear());
  const [calLocation, setCalLocation] = useState("");
  const [calDepartment, setCalDepartment] = useState("");
  const [genPola, setGenPola] = useState("");
  const [loadingCal, setLoadingCal] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [swapMode, setSwapMode] = useState(false);
  const [swapA, setSwapA] = useState(null); // { userId, day }
  const [cellEditor, setCellEditor] = useState(null);
  // { userId, userName, day, shift, highlightColor, note, isLembur, generatedShiftTypeId }

  const [editPrefId, setEditPrefId] = useState(null);
  const [prefFormData, setPrefFormData] = useState({});
  const [shiftFormData, setShiftFormData] = useState({ name: "", startTime: "", endTime: "" });

  const [autoEnabled, setAutoEnabled] = useState(scheduleConfig.scheduleAutoGenerateEnabled !== false);
  const [autoDay, setAutoDay] = useState(scheduleConfig.scheduleAutoGenerateDay ?? 15);
  const [lastKey, setLastKey] = useState(scheduleConfig.lastScheduleAutoGenerateKey || "");
  const [solverHealth, setSolverHealth] = useState(null);

  useEffect(() => {
    fetch("/api/schedules/solver-health")
      .then((r) => r.json())
      .then(setSolverHealth)
      .catch(() => setSolverHealth({ ok: false, error: "unreachable" }));
  }, []);

  const fetchSchedules = async () => {
    setLoadingCal(true);
    const start = new Date(calYear, calMonth, 1).toISOString();
    const end = new Date(calYear, calMonth + 1, 0, 23, 59, 59).toISOString();
    let url = `/api/schedules?start=${start}&end=${end}`;
    if (calLocation) url += `&locationId=${calLocation}`;
    const res = await fetch(url);
    if (res.ok) setSchedules(await res.json());
    setLoadingCal(false);
  };

  useEffect(() => {
    fetchSchedules();
  }, [calMonth, calYear, calLocation]);

  const handleGenerate = async () => {
    if (!isScheduleAdmin) return alert("Forbidden");
    if (
      !confirm(
        "Generate roster dengan engine POLA (OR-Tools) untuk bulan ini? Jadwal existing bulan ini akan ditimpa."
      )
    )
      return;

    setGenerating(true);
    try {
      const body = {
        mode: "pola",
        year: calYear,
        month: calMonth + 1,
        ...(calDepartment ? { departmentId: parseInt(calDepartment, 10) } : {}),
        ...(genPola ? { pola: genPola } : {}),
      };
      const res = await fetch("/api/schedules/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (!res.ok) {
        alert(`Error: ${data.error || "gagal"}`);
        return;
      }
      const lines = (data.results || [])
        .map((r) =>
          r.ok === false || r.error
            ? `✗ ${r.department || r.departmentId}: ${r.error || "failed"}`
            : `✓ ${r.department || r.departmentId}: ${r.pola} (${r.count} rows)`
        )
        .join("\n");
      alert(`Generate selesai:\n${lines || "OK"}`);
      fetchSchedules();
    } finally {
      setGenerating(false);
    }
  };

  const saveDeptPola = async (deptId, patch) => {
    const res = await fetch(`/api/departments/${deptId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(patch),
    });
    if (!res.ok) {
      const err = await res.json();
      alert(err.error || "Failed");
      return;
    }
    const updated = await res.json();
    setDepartments((prev) => prev.map((d) => (d.id === deptId ? { ...d, ...updated } : d)));
  };

  const cellDateStr = (day) =>
    `${calYear}-${String(calMonth + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`;

  const handleExportExcel = () => {
    const rows = [];
    for (const group of groupedRows) {
      rows.push({
        name: `▸ ${group.deptName}`,
        cells: Object.fromEntries(dayHeaders.map((d) => [d, ""])),
      });
      for (const row of group.rows) {
        rows.push({
          name: row.user.name || row.user.email,
          cells: Object.fromEntries(
            dayHeaders.map((d) => {
              if (!Object.prototype.hasOwnProperty.call(row.days, d)) return [d, ""];
              const cell = row.days[d];
              const st = cell?.shiftType;
              return [d, st == null ? "OFF" : st.name];
            })
          ),
        });
      }
    }
    exportScheduleMatrixExcel({
      title: "Jadwal Shift NOC",
      year: calYear,
      month: calMonth + 1,
      dayHeaders,
      rows,
      filename: `Jadwal_${calYear}-${String(calMonth + 1).padStart(2, "0")}.xls`,
    });
  };

  const patchCell = async (userId, day, payload) => {
    const res = await fetch("/api/schedules", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ userId, date: cellDateStr(day), ...payload }),
    });
    const data = await res.json();
    if (!res.ok) {
      alert(data.error || "Gagal update");
      return false;
    }
    await fetchSchedules();
    return true;
  };

  const saveCellEditor = async () => {
    if (!cellEditor) return;
    const ok = await patchCell(cellEditor.userId, cellEditor.day, {
      shift: cellEditor.shift,
      highlightColor: cellEditor.highlightColor,
      note: cellEditor.note,
      isLembur: cellEditor.isLembur,
    });
    if (ok) setCellEditor(null);
  };

  const handleCellClick = async (userId, day, meta = {}) => {
    if (!isEditor) {
      if (meta.note) alert(`Catatan:\n${meta.note}`);
      return;
    }

    if (swapMode) {
      if (!swapA) {
        setSwapA({ userId, day });
        return;
      }
      if (swapA.userId === userId && swapA.day === day) {
        setSwapA(null);
        return;
      }
      const res = await fetch("/api/schedules", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "swap",
          a: { userId: swapA.userId, date: cellDateStr(swapA.day) },
          b: { userId, date: cellDateStr(day) },
        }),
      });
      const data = await res.json();
      if (!res.ok) alert(data.error || "Swap gagal");
      setSwapA(null);
      await fetchSchedules();
      return;
    }

    const userRow = Object.values(gridData).find((r) => r.user.id === userId);
    const cell = meta.exists
      ? meta
      : { shiftType: null, highlightColor: null, note: "", exists: false };
    const shiftName =
      cell.shiftType && cell.shiftType.name
        ? cell.shiftType.name
        : cell.exists
          ? "OFF"
          : "OFF";
    setCellEditor({
      userId,
      userName: userRow?.user?.name || userRow?.user?.email || `#${userId}`,
      day,
      shift: shiftName,
      highlightColor: cell.highlightColor || null,
      note: cell.note || "",
      isLembur: !!cell.isLembur,
      generatedShiftTypeId: cell.generatedShiftTypeId ?? null,
    });
  };

  const saveAutoConfig = async () => {
    const res = await fetch("/api/schedules/settings", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        scheduleAutoGenerateEnabled: autoEnabled,
        scheduleAutoGenerateDay: parseInt(autoDay, 10) || 15,
      }),
    });
    if (res.ok) alert("Auto-generate settings saved");
    else alert("Failed to save settings");
  };

  const forceAutoGenerate = async () => {
    if (!confirm("Force generate jadwal bulan berikutnya sekarang?")) return;
    const res = await fetch("/api/schedules/auto-generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ force: true }),
    });
    const data = await res.json();
    if (!res.ok) alert(data.error || "Failed");
    else {
      setLastKey(data.key || "");
      alert(`Auto-generate target ${data.key}:\n${JSON.stringify(data.results, null, 2).slice(0, 800)}`);
    }
  };

  const handleSavePreference = async (userId) => {
    const res = await fetch("/api/schedules/preferences", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        userId,
        scheduleMode: prefFormData.scheduleMode,
        fixedShiftId: prefFormData.fixedShiftId,
        fixedOffDays: prefFormData.fixedOffDays,
        scheduleFlag: prefFormData.scheduleFlag,
      }),
    });
    if (res.ok) {
      setUsers((prev) =>
        prev.map((u) =>
          u.id === userId
            ? {
                ...u,
                scheduleFlag: prefFormData.scheduleFlag || u.scheduleFlag,
                schedulePreference: {
                  ...(u.schedulePreference || {}),
                  scheduleMode: prefFormData.scheduleMode,
                  fixedShiftId: prefFormData.fixedShiftId
                    ? parseInt(prefFormData.fixedShiftId, 10)
                    : null,
                  fixedOffDays: JSON.stringify(prefFormData.fixedOffDays || []),
                },
              }
            : u
        )
      );
      setEditPrefId(null);
      router.refresh();
    }
  };

  const toggleOffDay = (dayIndex) => {
    setPrefFormData((prev) => {
      const current = prev.fixedOffDays || [];
      if (current.includes(dayIndex))
        return { ...prev, fixedOffDays: current.filter((d) => d !== dayIndex) };
      return { ...prev, fixedOffDays: [...current, dayIndex] };
    });
  };

  const daysInMonth = new Date(calYear, calMonth + 1, 0).getDate();
  const dayHeaders = Array.from({ length: daysInMonth }, (_, i) => i + 1);

  const gridData = {};
  schedules.forEach((s) => {
    if (calDepartment && String(s.user?.departmentId) !== String(calDepartment)) return;
    if (!gridData[s.userId]) gridData[s.userId] = { user: s.user, days: {} };
    const dateStr = toDateOnlyString(s.date);
    const day = dateStr ? parseInt(dateStr.slice(8, 10), 10) : new Date(s.date).getUTCDate();
    gridData[s.userId].days[day] = {
      shiftType: s.shiftType,
      highlightColor: s.highlightColor || null,
      note: s.note || null,
      isLembur: !!s.isLembur,
      generatedShiftTypeId: s.generatedShiftTypeId ?? null,
      exists: true,
    };
  });

  // Group employees by department (stable order from departments prop, then leftovers)
  const deptOrder = new Map(departments.map((d, i) => [d.id, i]));
  const byDept = {};
  Object.values(gridData).forEach((row) => {
    const deptId = row.user?.departmentId ?? 0;
    const deptName =
      row.user?.department?.name ||
      departments.find((d) => d.id === deptId)?.name ||
      "Tanpa Departemen";
    if (!byDept[deptId]) byDept[deptId] = { deptId, deptName, rows: [] };
    byDept[deptId].rows.push(row);
  });
  Object.values(byDept).forEach((g) => {
    g.rows.sort((a, b) =>
      String(a.user?.name || a.user?.email || "").localeCompare(
        String(b.user?.name || b.user?.email || ""),
        "id"
      )
    );
  });
  const groupedRows = Object.values(byDept).sort((a, b) => {
    const ai = deptOrder.has(a.deptId) ? deptOrder.get(a.deptId) : 999;
    const bi = deptOrder.has(b.deptId) ? deptOrder.get(b.deptId) : 999;
    if (ai !== bi) return ai - bi;
    return a.deptName.localeCompare(b.deptName, "id");
  });

  const monthName = new Date(calYear, calMonth, 1).toLocaleDateString("id-ID", {
    month: "long",
  });

  const fairnessCards = (() => {
    const buildForDept = (deptId, deptName) => {
      const pola =
        departments.find((d) => String(d.id) === String(deptId))?.schedulePola || "POLA_1";
      return {
        deptId,
        deptName,
        fairness: buildDeptSummaries({
          schedules: schedules.filter(
            (s) => String(s.user?.departmentId) === String(deptId)
          ),
          pola,
          year: calYear,
          month: calMonth + 1,
        }),
      };
    };
    if (calDepartment) {
      const dept = departments.find((d) => String(d.id) === String(calDepartment));
      return [buildForDept(calDepartment, dept?.name || "Departemen")];
    }
    return groupedRows.map((g) => buildForDept(g.deptId, g.deptName));
  })();

  const totalHoursByUserId = new Map();
  for (const card of fairnessCards) {
    for (const r of card.fairness.rows) {
      totalHoursByUserId.set(r.userId, r.totalHours);
    }
  }

  return (
    <div>
      <div
        style={{
          marginBottom: "1rem",
          padding: "0.75rem 1rem",
          borderRadius: 8,
          background: solverHealth?.ok ? "#ecfdf5" : "#fef2f2",
          border: `1px solid ${solverHealth?.ok ? "#6ee7b7" : "#fecaca"}`,
          fontSize: "0.9rem",
        }}
      >
        <strong>Shift solver:</strong>{" "}
        {solverHealth == null
          ? "checking…"
          : solverHealth.ok
            ? "online (OR-Tools ready)"
            : `offline — ${solverHealth.error || "unreachable"}`}
        <button
          type="button"
          className="secondary-btn"
          style={{ width: "auto", marginLeft: 12, padding: "0.25rem 0.6rem", fontSize: "0.8rem" }}
          onClick={() => {
            setSolverHealth(null);
            fetch("/api/schedules/solver-health")
              .then((r) => r.json())
              .then(setSolverHealth)
              .catch(() => setSolverHealth({ ok: false, error: "unreachable" }));
          }}
        >
          Refresh
        </button>
      </div>

      <div
        style={{
          display: "flex",
          gap: "1rem",
          marginBottom: "1.5rem",
          borderBottom: "1px solid #e2e8f0",
          paddingBottom: "1rem",
          flexWrap: "wrap",
        }}
      >
        <button
          onClick={() => setActiveTab("calendar")}
          className={activeTab === "calendar" ? "primary-btn" : "secondary-btn"}
          style={{ width: "auto" }}
        >
          Schedule Grid
        </button>
        {isScheduleAdmin && (
          <button
            onClick={() => setActiveTab("pola")}
            className={activeTab === "pola" ? "primary-btn" : "secondary-btn"}
            style={{ width: "auto" }}
          >
            Pola & Auto-Gen
          </button>
        )}
        {isScheduleAdmin && (
          <button
            onClick={() => setActiveTab("preferences")}
            className={activeTab === "preferences" ? "primary-btn" : "secondary-btn"}
            style={{ width: "auto" }}
          >
            User Preferences
          </button>
        )}
        {isScheduleAdmin && (
          <button
            onClick={() => setActiveTab("types")}
            className={activeTab === "types" ? "primary-btn" : "secondary-btn"}
            style={{ width: "auto" }}
          >
            Shift Types
          </button>
        )}
      </div>

      {activeTab === "calendar" && (
        <div className="card" style={{ padding: 0, overflow: "hidden" }}>
          <div
            style={{
              padding: "1.5rem",
              background: "#f8fafc",
              borderBottom: "1px solid #e2e8f0",
              display: "flex",
              justifyContent: "space-between",
              flexWrap: "wrap",
              gap: "1rem",
            }}
          >
            <div style={{ display: "flex", gap: "0.75rem", alignItems: "center", flexWrap: "wrap" }}>
              <select
                value={calMonth}
                onChange={(e) => setCalMonth(parseInt(e.target.value, 10))}
                style={{ padding: "0.5rem", borderRadius: 4, border: "1px solid #cbd5e1" }}
              >
                {Array.from({ length: 12 }).map((_, i) => (
                  <option key={i} value={i}>
                    {new Date(2000, i).toLocaleString("default", { month: "long" })}
                  </option>
                ))}
              </select>
              <select
                value={calYear}
                onChange={(e) => setCalYear(parseInt(e.target.value, 10))}
                style={{ padding: "0.5rem", borderRadius: 4, border: "1px solid #cbd5e1" }}
              >
                <option value={new Date().getFullYear()}>{new Date().getFullYear()}</option>
                <option value={new Date().getFullYear() + 1}>{new Date().getFullYear() + 1}</option>
              </select>
              <select
                value={calDepartment}
                onChange={(e) => setCalDepartment(e.target.value)}
                style={{ padding: "0.5rem", borderRadius: 4, border: "1px solid #cbd5e1" }}
              >
                <option value="">All Departments</option>
                {departments.map((d) => (
                  <option key={d.id} value={d.id}>
                    {d.name} ({d.schedulePola || "POLA_1"}
                    {d.scheduleEnabled === false ? ", skip" : ""})
                  </option>
                ))}
              </select>
              <select
                value={calLocation}
                onChange={(e) => setCalLocation(e.target.value)}
                style={{ padding: "0.5rem", borderRadius: 4, border: "1px solid #cbd5e1" }}
              >
                <option value="">All Locations</option>
                {locations.map((loc) => (
                  <option key={loc.id} value={loc.id}>
                    {loc.city}
                  </option>
                ))}
              </select>
              {isScheduleAdmin && (
                <select
                  value={genPola}
                  onChange={(e) => setGenPola(e.target.value)}
                  style={{ padding: "0.5rem", borderRadius: 4, border: "1px solid #cbd5e1" }}
                  title="Override pola for this run (blank = department default)"
                >
                  <option value="">Pola: dept default</option>
                  {SCHEDULE_POLAS.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.label}
                    </option>
                  ))}
                </select>
              )}
            </div>
            <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap" }}>
              <button
                type="button"
                className="secondary-btn"
                style={{ width: "auto" }}
                onClick={handleExportExcel}
              >
                Export Excel
              </button>
              {isEditor && (
                <button
                  type="button"
                  className="secondary-btn"
                  style={{
                    width: "auto",
                    background: swapMode ? "#fef3c7" : undefined,
                    borderColor: swapMode ? "#f59e0b" : undefined,
                  }}
                  onClick={() => {
                    setSwapMode((v) => !v);
                    setSwapA(null);
                  }}
                >
                  {swapMode
                    ? swapA
                      ? "Swap: pilih sel ke-2…"
                      : "Swap: pilih sel ke-1…"
                    : "Mode Swap"}
                </button>
              )}
              {isScheduleAdmin && (
                <button
                  onClick={handleGenerate}
                  disabled={generating}
                  className="primary-btn"
                  style={{ width: "auto", background: "#0f766e" }}
                >
                  {generating ? "Generating…" : "Generate POLA Roster"}
                </button>
              )}
            </div>
          </div>
          <p style={{ margin: "0 1.5rem", fontSize: "0.8rem", color: "#64748b" }}>
            {isEditor
              ? "Klik sel untuk ubah shift, stabilo, atau catatan. Mode Swap untuk tukar dua sel."
              : "Klik sel yang bertanda catatan untuk membaca catatan."}
          </p>

          <div style={{ overflowX: "auto", padding: "1.5rem" }}>
            {!loadingCal && fairnessCards.length > 0 && (
              <div style={{ marginBottom: "1.25rem", display: "flex", flexDirection: "column", gap: "1rem" }}>
                {fairnessCards.map((card) => (
                  <div
                    key={`fairness-${card.deptId}`}
                    style={{
                      border: "1px solid #e2e8f0",
                      borderRadius: 8,
                      overflow: "hidden",
                    }}
                  >
                    <div style={{ background: "#0f172a", color: "#fff", padding: "0.5rem 0.75rem" }}>
                      <strong>
                        {card.deptName} — Ringkasan fairness {monthName} {calYear}
                      </strong>
                      <div style={{ fontSize: "0.8rem", opacity: 0.75 }}>
                        Distribusi shift per orang (fairness)
                      </div>
                    </div>
                    <div style={{ overflowX: "auto" }}>
                      <table
                        style={{
                          width: "100%",
                          borderCollapse: "collapse",
                          fontSize: "0.85rem",
                        }}
                      >
                        <thead>
                          <tr>
                            <th
                              style={{
                                padding: "0.5rem 0.75rem",
                                textAlign: "left",
                                borderBottom: "1px solid #e2e8f0",
                                background: "#f8fafc",
                              }}
                            >
                              Nama
                            </th>
                            {card.fairness.columns.map((col) => (
                              <th
                                key={col.key}
                                style={{
                                  padding: "0.5rem 0.75rem",
                                  textAlign: "center",
                                  borderBottom: "1px solid #e2e8f0",
                                  background: "#f8fafc",
                                }}
                              >
                                {col.label}
                              </th>
                            ))}
                          </tr>
                        </thead>
                        <tbody>
                          {card.fairness.rows.length === 0 ? (
                            <tr>
                              <td
                                colSpan={card.fairness.columns.length + 1}
                                style={{ padding: "0.75rem", color: "#94a3b8" }}
                              >
                                Belum ada data jadwal.
                              </td>
                            </tr>
                          ) : (
                            card.fairness.rows.map((r) => (
                              <tr key={r.userId}>
                                <td
                                  style={{
                                    padding: "0.45rem 0.75rem",
                                    borderBottom: "1px solid #f1f5f9",
                                    textAlign: "left",
                                    fontWeight: 600,
                                  }}
                                >
                                  {r.name}
                                </td>
                                {card.fairness.columns.map((col) => (
                                  <td
                                    key={col.key}
                                    style={{
                                      padding: "0.45rem 0.75rem",
                                      borderBottom: "1px solid #f1f5f9",
                                      textAlign: "center",
                                    }}
                                  >
                                    {r[col.key]}
                                  </td>
                                ))}
                              </tr>
                            ))
                          )}
                        </tbody>
                      </table>
                    </div>
                  </div>
                ))}
              </div>
            )}
            {loadingCal ? (
              <p>Loading Schedule Matrix...</p>
            ) : (
              <table
                style={{
                  width: "100%",
                  borderCollapse: "collapse",
                  textAlign: "center",
                  minWidth: 1200,
                }}
              >
                <thead>
                  <tr>
                    <th
                      style={{
                        padding: "0.75rem",
                        background: "#e2e8f0",
                        border: "1px solid #cbd5e1",
                        textAlign: "left",
                        position: "sticky",
                        left: 0,
                        zIndex: 1,
                      }}
                    >
                      Employee / Team
                    </th>
                    <th
                      style={{
                        padding: "0.5rem",
                        background: "#e2e8f0",
                        border: "1px solid #cbd5e1",
                        fontSize: "0.8rem",
                        minWidth: 72,
                        whiteSpace: "nowrap",
                      }}
                    >
                      Total Jam
                    </th>
                    {dayHeaders.map((d) => {
                      const dateObj = new Date(calYear, calMonth, d);
                      const isWeekend = dateObj.getDay() === 0 || dateObj.getDay() === 6;
                      return (
                        <th
                          key={d}
                          style={{
                            padding: "0.5rem",
                            background: isWeekend ? "#fecaca" : "#f1f5f9",
                            border: "1px solid #cbd5e1",
                            fontSize: "0.8rem",
                            minWidth: 40,
                          }}
                        >
                          <div>{d}</div>
                          <div style={{ fontSize: "0.65rem", color: "#64748b" }}>
                            {dateObj.toLocaleDateString("en-US", { weekday: "short" })}
                          </div>
                        </th>
                      );
                    })}
                  </tr>
                </thead>
                <tbody>
                  {groupedRows.map((group) => {
                    const colors = departmentColor(group.deptId);
                    return (
                      <Fragment key={`dept-${group.deptId}`}>
                        <tr>
                          <td
                            colSpan={daysInMonth + 2}
                            style={{
                              padding: "0.55rem 0.75rem",
                              textAlign: "left",
                              fontWeight: 700,
                              fontSize: "0.85rem",
                              letterSpacing: "0.02em",
                              color: colors.text,
                              background: colors.header,
                              border: `1px solid ${colors.accent}33`,
                              position: "sticky",
                              left: 0,
                              zIndex: 2,
                            }}
                          >
                            {group.deptName}
                            <span style={{ fontWeight: 500, opacity: 0.75, marginLeft: 8 }}>
                              ({group.rows.length} orang)
                            </span>
                          </td>
                        </tr>
                        {group.rows.map((row) => (
                          <tr key={row.user.id} style={{ background: colors.bg }}>
                            <td
                              style={{
                                padding: "0.75rem",
                                border: "1px solid #cbd5e1",
                                textAlign: "left",
                                fontWeight: "bold",
                                background: colors.bg,
                                color: colors.text,
                                position: "sticky",
                                left: 0,
                                zIndex: 1,
                                borderLeft: `4px solid ${colors.accent}`,
                              }}
                            >
                              {row.user.name || row.user.email || `#${row.user.id}`}
                              <br />
                              <span style={{ fontSize: "0.7rem", opacity: 0.75, fontWeight: "normal" }}>
                                {row.user.location?.city || "No Location"}
                              </span>
                            </td>
                            <td
                              style={{
                                padding: "0.5rem",
                                border: "1px solid #cbd5e1",
                                background: colors.bg,
                                color: colors.text,
                                fontWeight: 600,
                                fontSize: "0.8rem",
                                whiteSpace: "nowrap",
                              }}
                            >
                              {totalHoursByUserId.has(row.user.id)
                                ? totalHoursByUserId.get(row.user.id)
                                : "—"}
                            </td>
                            {dayHeaders.map((d) => {
                              const cell = row.days[d];
                              const isPending = !cell;
                              const isOff = cell && cell.shiftType == null;
                              const shift = cell?.shiftType;
                              const selected =
                                swapA && swapA.userId === row.user.id && swapA.day === d;
                              const cellDate = new Date(calYear, calMonth, d);
                              const isWeekend =
                                cellDate.getDay() === 0 || cellDate.getDay() === 6;
                              const rowPola =
                                departments.find(
                                  (dep) => String(dep.id) === String(row.user.departmentId)
                                )?.schedulePola || "";
                              const isCorePola =
                                rowPola === "POLA_2" || rowPola === "NOC_CORE";
                              const shiftLabel = isOff
                                ? "OFF"
                                : isPending
                                  ? "-"
                                  : isCorePola &&
                                      isWeekend &&
                                      shift?.name &&
                                      ["S1", "S2", "S1+OC"].includes(shift.name)
                                    ? `${shift.name} (WFH)`
                                    : shift?.name;
                              const shiftColor = isPending
                                ? null
                                : shiftCellColor(isOff ? null : shift?.name);
                              const bg = selected
                                ? "#fef3c7"
                                : cell?.highlightColor
                                  ? cell.highlightColor
                                  : isPending
                                    ? colors.bg
                                    : shiftColor.bg;
                              const cellText = cell?.highlightColor
                                ? colors.text
                                : shiftColor?.text || colors.text;
                              return (
                                <td
                                  key={d}
                                  onClick={() =>
                                    handleCellClick(row.user.id, d, {
                                      ...(cell || { exists: false }),
                                      exists: !!cell,
                                    })
                                  }
                                  title={
                                    cell?.note
                                      ? cell.note
                                      : isEditor
                                        ? "Klik untuk edit / swap"
                                        : undefined
                                  }
                                  style={{
                                    padding: "0.5rem",
                                    border: selected
                                      ? "2px solid #f59e0b"
                                      : cell?.highlightColor
                                        ? `2px solid ${colors.accent}`
                                        : "1px solid #cbd5e1",
                                    fontSize: "0.75rem",
                                    background: bg,
                                    cursor: isEditor || cell?.note ? "pointer" : "default",
                                    color: cellText,
                                    position: "relative",
                                  }}
                                >
                                  {isOff ? (
                                    <span style={{ fontWeight: 600, opacity: 0.85 }}>OFF</span>
                                  ) : isPending ? (
                                    <span style={{ opacity: 0.35 }}>-</span>
                                  ) : (
                                    <div style={{ fontWeight: "bold", lineHeight: 1.15 }}>
                                      {shiftLabel}
                                    </div>
                                  )}
                                  {cell?.note ? (
                                    <span
                                      style={{
                                        position: "absolute",
                                        top: 2,
                                        right: 3,
                                        fontSize: "0.65rem",
                                        opacity: 0.8,
                                      }}
                                      aria-hidden
                                    >
                                      ✎
                                    </span>
                                  ) : null}
                                </td>
                              );
                            })}
                          </tr>
                        ))}
                      </Fragment>
                    );
                  })}
                  {groupedRows.length === 0 && (
                    <tr>
                      <td colSpan={daysInMonth + 2} style={{ padding: "2rem", color: "#94a3b8" }}>
                        No schedules generated for this range.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            )}
            {groupedRows.length > 0 && (
              <div
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  gap: "0.75rem",
                  marginTop: "1rem",
                  fontSize: "0.8rem",
                  alignItems: "center",
                }}
              >
                <span style={{ color: "#64748b", fontWeight: 600, marginRight: 4 }}>Shift:</span>
                {SHIFT_COLOR_LEGEND.map((sc) => (
                  <span
                    key={`shift-${sc.label}`}
                    style={{
                      display: "inline-flex",
                      alignItems: "center",
                      gap: 6,
                      padding: "0.25rem 0.6rem",
                      borderRadius: 4,
                      background: sc.bg,
                      color: sc.text,
                      border: "1px solid #cbd5e1",
                      fontWeight: 600,
                    }}
                  >
                    {sc.label}
                  </span>
                ))}
                <span
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    padding: "0.25rem 0.6rem",
                    borderRadius: 4,
                    border: "1px dashed #94a3b8",
                    color: "#475569",
                    fontSize: "0.75rem",
                  }}
                  title="Khusus POLA_2 / NOC Core di Sabtu–Minggu"
                >
                  (WFH) = weekend duty
                </span>
                <span style={{ color: "#94a3b8", margin: "0 0.25rem" }}>|</span>
                <span style={{ color: "#64748b", fontWeight: 600, marginRight: 4 }}>Dept:</span>
                {groupedRows.map((g) => {
                  const c = departmentColor(g.deptId);
                  return (
                    <span
                      key={`leg-${g.deptId}`}
                      style={{
                        display: "inline-flex",
                        alignItems: "center",
                        gap: 6,
                        padding: "0.25rem 0.6rem",
                        borderRadius: 999,
                        background: c.header,
                        color: c.text,
                        border: `1px solid ${c.accent}44`,
                      }}
                    >
                      <span
                        style={{
                          width: 10,
                          height: 10,
                          borderRadius: 2,
                          background: c.accent,
                          display: "inline-block",
                        }}
                      />
                      {g.deptName}
                    </span>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      )}

      {activeTab === "pola" && isScheduleAdmin && (
        <div style={{ display: "grid", gap: "1.5rem" }}>
          <div className="card">
            <h2 style={{ marginTop: 0 }}>Default Pola per Departemen</h2>
            <p style={{ color: "#64748b" }}>
              Centang <strong>Generate</strong> hanya untuk dept yang butuh roster (NOC/CS). Yang tidak dicentang
              di-skip saat auto-generate / generate semua. Engine OR-Tools (adopsi absen). Auto tanggal {autoDay}{" "}
              generate <strong>bulan berikutnya</strong>.
            </p>
            <table className="table" style={{ width: "100%", borderCollapse: "collapse" }}>
              <thead>
                <tr style={{ background: "#f1f5f9" }}>
                  <th style={{ padding: "0.75rem", textAlign: "left" }}>Generate</th>
                  <th style={{ padding: "0.75rem", textAlign: "left" }}>Department</th>
                  <th style={{ padding: "0.75rem", textAlign: "left" }}>Default Pola</th>
                </tr>
              </thead>
              <tbody>
                {departments.map((d) => (
                  <tr key={d.id} style={{ borderBottom: "1px solid #e2e8f0" }}>
                    <td style={{ padding: "0.75rem" }}>
                      <input
                        type="checkbox"
                        checked={d.scheduleEnabled !== false}
                        onChange={(e) => saveDeptPola(d.id, { scheduleEnabled: e.target.checked })}
                        title="Ikut generate roster / auto-absen"
                      />
                    </td>
                    <td style={{ padding: "0.75rem", fontWeight: 600 }}>
                      {d.name}
                      {d.scheduleEnabled === false && (
                        <span style={{ marginLeft: 8, fontSize: "0.75rem", color: "#94a3b8", fontWeight: 400 }}>
                          (skip)
                        </span>
                      )}
                    </td>
                    <td style={{ padding: "0.75rem" }}>
                      <select
                        value={d.schedulePola || "POLA_1"}
                        disabled={d.scheduleEnabled === false}
                        onChange={(e) => saveDeptPola(d.id, { schedulePola: e.target.value })}
                        style={{ padding: "0.5rem", minWidth: 280 }}
                      >
                        {SCHEDULE_POLAS.map((p) => (
                          <option key={p.id} value={p.id}>
                            {p.label}
                          </option>
                        ))}
                      </select>
                    </td>
                  </tr>
                ))}
                {departments.length === 0 && (
                  <tr>
                    <td colSpan={3} style={{ padding: "1rem", color: "#94a3b8" }}>
                      Belum ada department.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
            <div style={{ marginTop: "1rem", fontSize: "0.85rem", color: "#64748b" }}>
              {SCHEDULE_POLAS.map((p) => (
                <div key={p.id} style={{ marginBottom: 4 }}>
                  <strong>{p.id}</strong> — {p.summary}
                </div>
              ))}
            </div>
          </div>

          <div className="card">
            <h2 style={{ marginTop: 0 }}>Auto-Generate</h2>
            <p style={{ color: "#64748b" }}>
              Setiap tanggal yang dikonfigurasi, sistem generate roster <strong>bulan depan</strong> untuk
              semua departemen (pola default masing-masing). Last run key:{" "}
              <code>{lastKey || "—"}</code>
            </p>
            <label style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: "0.75rem" }}>
              <input
                type="checkbox"
                checked={autoEnabled}
                onChange={(e) => setAutoEnabled(e.target.checked)}
              />
              Enable auto-generate
            </label>
            <label style={{ display: "block", marginBottom: "0.75rem" }}>
              Tanggal tiap bulan{" "}
              <input
                type="number"
                min={1}
                max={28}
                value={autoDay}
                onChange={(e) => setAutoDay(e.target.value)}
                style={{ width: 64, padding: "0.4rem", marginLeft: 8 }}
              />
            </label>
            <div style={{ display: "flex", gap: "0.75rem", flexWrap: "wrap" }}>
              <button type="button" className="primary-btn" style={{ width: "auto" }} onClick={saveAutoConfig}>
                Save settings
              </button>
              <button
                type="button"
                className="secondary-btn"
                style={{ width: "auto" }}
                onClick={forceAutoGenerate}
              >
                Force run now (next month)
              </button>
            </div>
          </div>
        </div>
      )}

      {activeTab === "preferences" && isScheduleAdmin && (
        <div className="card">
          <h2 style={{ marginTop: 0 }}>Team Roster Preferences</h2>
          <p style={{ color: "#64748b", marginBottom: "1.5rem" }}>
            Flag (Umum/Kristen/Kuliah) dipakai constraint POLA. Mode FIXED/RANDOM hanya untuk legacy
            generator.
          </p>
          <table className="table" style={{ width: "100%", textAlign: "left", borderCollapse: "collapse" }}>
            <thead>
              <tr style={{ background: "#f1f5f9" }}>
                <th style={{ padding: "1rem" }}>User</th>
                <th style={{ padding: "1rem" }}>Flag</th>
                <th style={{ padding: "1rem" }}>Mode</th>
                <th style={{ padding: "1rem" }}>Fixed Shift</th>
                <th style={{ padding: "1rem" }}>Fixed Off-Days</th>
                <th style={{ padding: "1rem" }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {users.map((u) => {
                const pref = u.schedulePreference || {
                  scheduleMode: "RANDOM",
                  fixedOffDays: "[]",
                  fixedShiftId: null,
                };
                let offDays = [];
                try {
                  offDays = JSON.parse(pref.fixedOffDays);
                } catch {
                  /* ignore */
                }
                const isEditing = editPrefId === u.id;
                const daysOfWeek = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
                return (
                  <tr key={u.id} style={{ borderBottom: "1px solid #e2e8f0" }}>
                    <td style={{ padding: "1rem", fontWeight: "bold" }}>{u.name || u.email}</td>
                    {isEditing ? (
                      <>
                        <td style={{ padding: "1rem" }}>
                          <select
                            value={prefFormData.scheduleFlag || "Umum"}
                            onChange={(e) =>
                              setPrefFormData({ ...prefFormData, scheduleFlag: e.target.value })
                            }
                          >
                            {SCHEDULE_FLAGS.map((f) => (
                              <option key={f} value={f}>
                                {f}
                              </option>
                            ))}
                          </select>
                        </td>
                        <td style={{ padding: "1rem" }}>
                          <select
                            value={prefFormData.scheduleMode}
                            onChange={(e) =>
                              setPrefFormData({ ...prefFormData, scheduleMode: e.target.value })
                            }
                          >
                            <option value="RANDOM">Random Fill</option>
                            <option value="ROTATING">Rotating</option>
                            <option value="FIXED">Fixed</option>
                          </select>
                        </td>
                        <td style={{ padding: "1rem" }}>
                          <select
                            disabled={prefFormData.scheduleMode !== "FIXED"}
                            value={prefFormData.fixedShiftId || ""}
                            onChange={(e) =>
                              setPrefFormData({ ...prefFormData, fixedShiftId: e.target.value })
                            }
                          >
                            <option value="">--</option>
                            {shiftTypes.map((st) => (
                              <option key={st.id} value={st.id}>
                                {st.name}
                              </option>
                            ))}
                          </select>
                        </td>
                        <td style={{ padding: "1rem", fontSize: "0.8rem" }}>
                          <div style={{ display: "flex", gap: "0.2rem", flexWrap: "wrap" }}>
                            {daysOfWeek.map((dayName, idx) => (
                              <label
                                key={idx}
                                style={{
                                  background: prefFormData.fixedOffDays?.includes(idx)
                                    ? "#fca5a5"
                                    : "#f1f5f9",
                                  padding: "0.2rem 0.4rem",
                                  borderRadius: 4,
                                  cursor: "pointer",
                                }}
                              >
                                <input
                                  type="checkbox"
                                  style={{ display: "none" }}
                                  checked={prefFormData.fixedOffDays?.includes(idx)}
                                  onChange={() => toggleOffDay(idx)}
                                />
                                {dayName}
                              </label>
                            ))}
                          </div>
                        </td>
                        <td style={{ padding: "1rem" }}>
                          <button
                            onClick={() => handleSavePreference(u.id)}
                            className="primary-btn"
                            style={{ width: "auto", padding: "0.4rem 0.8rem", marginRight: "0.5rem" }}
                          >
                            Save
                          </button>
                          <button
                            onClick={() => setEditPrefId(null)}
                            className="secondary-btn"
                            style={{ width: "auto", padding: "0.4rem 0.8rem" }}
                          >
                            Cancel
                          </button>
                        </td>
                      </>
                    ) : (
                      <>
                        <td style={{ padding: "1rem" }}>{u.scheduleFlag || "Umum"}</td>
                        <td style={{ padding: "1rem" }}>
                          <span className="badge">{pref.scheduleMode}</span>
                        </td>
                        <td style={{ padding: "1rem", color: "#64748b" }}>
                          {pref.scheduleMode === "FIXED" && pref.fixedShift ? pref.fixedShift.name : "-"}
                        </td>
                        <td style={{ padding: "1rem", fontSize: "0.8rem" }}>
                          {offDays.length > 0 ? offDays.map((d) => daysOfWeek[d]).join(", ") : "None"}
                        </td>
                        <td style={{ padding: "1rem" }}>
                          <button
                            onClick={() => {
                              setPrefFormData({
                                scheduleMode: pref.scheduleMode,
                                fixedShiftId: pref.fixedShiftId,
                                fixedOffDays: offDays,
                                scheduleFlag: u.scheduleFlag || "Umum",
                              });
                              setEditPrefId(u.id);
                            }}
                            style={{
                              padding: "0.4rem 0.8rem",
                              background: "#e2e8f0",
                              border: "none",
                              borderRadius: 4,
                              cursor: "pointer",
                            }}
                          >
                            Config
                          </button>
                        </td>
                      </>
                    )}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {activeTab === "types" && isScheduleAdmin && (
        <div className="card" style={{ maxWidth: 600 }}>
          <h2 style={{ marginTop: 0 }}>Shift Types</h2>
          <p style={{ color: "#64748b", fontSize: "0.9rem" }}>
            POLA engine memakai nama S1 / S2 / S3 / S1+OC (di-seed otomatis saat generate).
          </p>
          <form
            onSubmit={async (e) => {
              e.preventDefault();
              const res = await fetch("/api/schedules/types", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(shiftFormData),
              });
              if (res.ok) {
                setShiftTypes([...shiftTypes, await res.json()]);
                setShiftFormData({ name: "", startTime: "", endTime: "" });
              }
            }}
            style={{ display: "flex", gap: "1rem", marginBottom: "2rem", alignItems: "flex-end" }}
          >
            <div style={{ flex: 1 }}>
              <label style={{ display: "block", fontSize: "0.8rem", fontWeight: "bold" }}>Name</label>
              <input
                type="text"
                required
                value={shiftFormData.name}
                onChange={(e) => setShiftFormData({ ...shiftFormData, name: e.target.value })}
                style={{ width: "100%", padding: "0.5rem" }}
              />
            </div>
            <div>
              <label style={{ display: "block", fontSize: "0.8rem", fontWeight: "bold" }}>Start</label>
              <input
                type="time"
                required
                value={shiftFormData.startTime}
                onChange={(e) => setShiftFormData({ ...shiftFormData, startTime: e.target.value })}
                style={{ padding: "0.5rem" }}
              />
            </div>
            <div>
              <label style={{ display: "block", fontSize: "0.8rem", fontWeight: "bold" }}>End</label>
              <input
                type="time"
                required
                value={shiftFormData.endTime}
                onChange={(e) => setShiftFormData({ ...shiftFormData, endTime: e.target.value })}
                style={{ padding: "0.5rem" }}
              />
            </div>
            <button type="submit" className="primary-btn" style={{ width: "auto", padding: "0.6rem 1rem" }}>
              Add
            </button>
          </form>
          <ul style={{ listStyle: "none", padding: 0 }}>
            {shiftTypes.map((st) => (
              <li
                key={st.id}
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  padding: "1rem",
                  border: "1px solid #e2e8f0",
                  marginBottom: "0.5rem",
                  borderRadius: 4,
                  background: "#f8fafc",
                }}
              >
                <strong>{st.name}</strong>
                <span style={{ color: "#64748b" }}>
                  {st.startTime} to {st.endTime}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {cellEditor && (
        <div
          role="dialog"
          aria-modal="true"
          style={{
            position: "fixed",
            inset: 0,
            background: "rgba(15, 23, 42, 0.45)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 1000,
            padding: "1rem",
          }}
          onClick={() => setCellEditor(null)}
        >
          <div
            style={{
              background: "#fff",
              borderRadius: 8,
              padding: "1.25rem 1.5rem",
              width: "100%",
              maxWidth: 420,
              boxShadow: "0 20px 40px rgba(0,0,0,0.15)",
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <h3 style={{ margin: "0 0 0.25rem", fontSize: "1.1rem" }}>Edit sel</h3>
            <p style={{ margin: "0 0 1rem", color: "#64748b", fontSize: "0.875rem" }}>
              {cellEditor.userName} · tgl {cellEditor.day}/
              {calMonth + 1}/{calYear}
            </p>

            <label style={{ display: "block", fontSize: "0.8rem", fontWeight: 600, marginBottom: 4 }}>
              Shift
            </label>
            <select
              value={cellEditor.shift}
              onChange={(e) => {
                const shift = e.target.value;
                setCellEditor((c) => ({
                  ...c,
                  shift,
                  isLembur:
                    shift === "OFF" || !isWorkingShiftName(shift) ? false : c.isLembur,
                }));
              }}
              style={{
                width: "100%",
                padding: "0.5rem",
                marginBottom: "1rem",
                borderRadius: 4,
                border: "1px solid #cbd5e1",
              }}
            >
              <option value="OFF">OFF</option>
              {[...new Set(["S1", "S2", "S3", "S1+OC", ...shiftTypes.map((s) => s.name)])].map(
                (name) => (
                  <option key={name} value={name}>
                    {name}
                  </option>
                )
              )}
            </select>

            {cellEditor.shift !== "OFF" && isWorkingShiftName(cellEditor.shift) && (
              <div style={{ marginBottom: "1rem" }}>
                <label
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 8,
                    fontSize: "0.875rem",
                    fontWeight: 500,
                    cursor: "pointer",
                  }}
                >
                  <input
                    type="checkbox"
                    checked={!!cellEditor.isLembur}
                    onChange={(e) =>
                      setCellEditor((c) => ({ ...c, isLembur: e.target.checked }))
                    }
                  />
                  Lembur (panggil dari OFF)
                </label>
                {cellEditor.generatedShiftTypeId == null && (
                  <div style={{ fontSize: "0.75rem", color: "#64748b", marginTop: 4 }}>
                    Baseline generate: OFF — default dianggap lembur jika diisi shift kerja.
                  </div>
                )}
              </div>
            )}

            <label style={{ display: "block", fontSize: "0.8rem", fontWeight: 600, marginBottom: 6 }}>
              Stabilo
            </label>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: "1rem" }}>
              <button
                type="button"
                onClick={() => setCellEditor((c) => ({ ...c, highlightColor: null }))}
                style={{
                  width: 32,
                  height: 32,
                  borderRadius: 4,
                  border: !cellEditor.highlightColor ? "2px solid #0f172a" : "1px solid #cbd5e1",
                  background: "#fff",
                  cursor: "pointer",
                  fontSize: 11,
                }}
                title="Tanpa warna"
              >
                ✕
              </button>
              {HIGHLIGHT_COLORS.filter((c) => c.hex).map((c) => (
                <button
                  key={c.id}
                  type="button"
                  title={c.label}
                  onClick={() => setCellEditor((ed) => ({ ...ed, highlightColor: c.hex }))}
                  style={{
                    width: 32,
                    height: 32,
                    borderRadius: 4,
                    border:
                      cellEditor.highlightColor === c.hex
                        ? "2px solid #0f172a"
                        : "1px solid #94a3b8",
                    background: c.hex,
                    cursor: "pointer",
                  }}
                />
              ))}
            </div>

            <label style={{ display: "block", fontSize: "0.8rem", fontWeight: 600, marginBottom: 4 }}>
              Catatan
            </label>
            <textarea
              value={cellEditor.note}
              onChange={(e) => setCellEditor((c) => ({ ...c, note: e.target.value }))}
              rows={3}
              placeholder="Catatan untuk sel ini…"
              style={{
                width: "100%",
                padding: "0.5rem",
                marginBottom: "1.25rem",
                borderRadius: 4,
                border: "1px solid #cbd5e1",
                resize: "vertical",
                fontFamily: "inherit",
              }}
            />

            <div style={{ display: "flex", gap: 8, justifyContent: "flex-end" }}>
              <button
                type="button"
                className="secondary-btn"
                style={{ width: "auto" }}
                onClick={() => setCellEditor(null)}
              >
                Batal
              </button>
              <button
                type="button"
                className="primary-btn"
                style={{ width: "auto" }}
                onClick={saveCellEditor}
              >
                Simpan
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
