"use client";
import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { SCHEDULE_POLAS, SCHEDULE_FLAGS } from "@/lib/schedules/pola";

export default function SchedulesClient({
  initialShiftTypes,
  users: initialUsers,
  locations,
  departments: initialDepartments = [],
  currentUser,
  scheduleConfig = {},
}) {
  const router = useRouter();
  const [activeTab, setActiveTab] = useState("calendar");
  const [shiftTypes, setShiftTypes] = useState(initialShiftTypes);
  const [users, setUsers] = useState(initialUsers);
  const [departments, setDepartments] = useState(initialDepartments);

  const isAdminOrManager =
    currentUser.permissions?.includes("manage_schedules") || currentUser.role === "Admin";

  const [schedules, setSchedules] = useState([]);
  const [calMonth, setCalMonth] = useState(new Date().getMonth());
  const [calYear, setCalYear] = useState(new Date().getFullYear());
  const [calLocation, setCalLocation] = useState("");
  const [calDepartment, setCalDepartment] = useState("");
  const [genPola, setGenPola] = useState("");
  const [loadingCal, setLoadingCal] = useState(false);
  const [generating, setGenerating] = useState(false);

  const [editPrefId, setEditPrefId] = useState(null);
  const [prefFormData, setPrefFormData] = useState({});
  const [shiftFormData, setShiftFormData] = useState({ name: "", startTime: "", endTime: "" });

  const [autoEnabled, setAutoEnabled] = useState(scheduleConfig.scheduleAutoGenerateEnabled !== false);
  const [autoDay, setAutoDay] = useState(scheduleConfig.scheduleAutoGenerateDay ?? 15);
  const [lastKey, setLastKey] = useState(scheduleConfig.lastScheduleAutoGenerateKey || "");

  const fetchSchedules = async () => {
    setLoadingCal(true);
    const start = new Date(calYear, calMonth, 1).toISOString();
    const end = new Date(calYear, calMonth + 1, 0, 23, 59, 59).toISOString();
    let url = `/api/schedules?start=${start}&end=${end}`;
    if (calLocation) url += `&locationId=${calLocation}`;
    const res = await fetch(url);
    if (res.ok) setSchedules(await res.json());
    setLoadingCal(false);
  };

  useEffect(() => {
    fetchSchedules();
  }, [calMonth, calYear, calLocation]);

  const handleGenerate = async () => {
    if (!isAdminOrManager) return alert("Forbidden");
    if (
      !confirm(
        "Generate roster dengan engine POLA (OR-Tools) untuk bulan ini? Jadwal existing bulan ini akan ditimpa."
      )
    )
      return;

    setGenerating(true);
    try {
      const body = {
        mode: "pola",
        year: calYear,
        month: calMonth + 1,
        ...(calDepartment ? { departmentId: parseInt(calDepartment, 10) } : {}),
        ...(genPola ? { pola: genPola } : {}),
      };
      const res = await fetch("/api/schedules/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (!res.ok) {
        alert(`Error: ${data.error || "gagal"}`);
        return;
      }
      const lines = (data.results || [])
        .map((r) =>
          r.ok === false || r.error
            ? `✗ ${r.department || r.departmentId}: ${r.error || "failed"}`
            : `✓ ${r.department || r.departmentId}: ${r.pola} (${r.count} rows)`
        )
        .join("\n");
      alert(`Generate selesai:\n${lines || "OK"}`);
      fetchSchedules();
    } finally {
      setGenerating(false);
    }
  };

  const saveDeptPola = async (deptId, schedulePola) => {
    const res = await fetch(`/api/departments/${deptId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ schedulePola }),
    });
    if (!res.ok) {
      const err = await res.json();
      alert(err.error || "Failed");
      return;
    }
    const updated = await res.json();
    setDepartments((prev) => prev.map((d) => (d.id === deptId ? { ...d, ...updated } : d)));
  };

  const saveAutoConfig = async () => {
    const res = await fetch("/api/schedules/settings", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        scheduleAutoGenerateEnabled: autoEnabled,
        scheduleAutoGenerateDay: parseInt(autoDay, 10) || 15,
      }),
    });
    if (res.ok) alert("Auto-generate settings saved");
    else alert("Failed to save settings");
  };

  const forceAutoGenerate = async () => {
    if (!confirm("Force generate jadwal bulan berikutnya sekarang?")) return;
    const res = await fetch("/api/schedules/auto-generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ force: true }),
    });
    const data = await res.json();
    if (!res.ok) alert(data.error || "Failed");
    else {
      setLastKey(data.key || "");
      alert(`Auto-generate target ${data.key}:\n${JSON.stringify(data.results, null, 2).slice(0, 800)}`);
    }
  };

  const handleSavePreference = async (userId) => {
    const res = await fetch("/api/schedules/preferences", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        userId,
        scheduleMode: prefFormData.scheduleMode,
        fixedShiftId: prefFormData.fixedShiftId,
        fixedOffDays: prefFormData.fixedOffDays,
        scheduleFlag: prefFormData.scheduleFlag,
      }),
    });
    if (res.ok) {
      setUsers((prev) =>
        prev.map((u) =>
          u.id === userId
            ? {
                ...u,
                scheduleFlag: prefFormData.scheduleFlag || u.scheduleFlag,
                schedulePreference: {
                  ...(u.schedulePreference || {}),
                  scheduleMode: prefFormData.scheduleMode,
                  fixedShiftId: prefFormData.fixedShiftId
                    ? parseInt(prefFormData.fixedShiftId, 10)
                    : null,
                  fixedOffDays: JSON.stringify(prefFormData.fixedOffDays || []),
                },
              }
            : u
        )
      );
      setEditPrefId(null);
      router.refresh();
    }
  };

  const toggleOffDay = (dayIndex) => {
    setPrefFormData((prev) => {
      const current = prev.fixedOffDays || [];
      if (current.includes(dayIndex))
        return { ...prev, fixedOffDays: current.filter((d) => d !== dayIndex) };
      return { ...prev, fixedOffDays: [...current, dayIndex] };
    });
  };

  const daysInMonth = new Date(calYear, calMonth + 1, 0).getDate();
  const dayHeaders = Array.from({ length: daysInMonth }, (_, i) => i + 1);

  const gridData = {};
  schedules.forEach((s) => {
    if (calDepartment && String(s.user?.departmentId) !== String(calDepartment)) return;
    if (!gridData[s.userId]) gridData[s.userId] = { user: s.user, days: {} };
    const day = new Date(s.date).getDate();
    gridData[s.userId].days[day] = s.shiftType;
  });

  return (
    <div>
      <div
        style={{
          display: "flex",
          gap: "1rem",
          marginBottom: "1.5rem",
          borderBottom: "1px solid #e2e8f0",
          paddingBottom: "1rem",
          flexWrap: "wrap",
        }}
      >
        <button
          onClick={() => setActiveTab("calendar")}
          className={activeTab === "calendar" ? "primary-btn" : "secondary-btn"}
          style={{ width: "auto" }}
        >
          Schedule Grid
        </button>
        {isAdminOrManager && (
          <button
            onClick={() => setActiveTab("pola")}
            className={activeTab === "pola" ? "primary-btn" : "secondary-btn"}
            style={{ width: "auto" }}
          >
            Pola & Auto-Gen
          </button>
        )}
        {isAdminOrManager && (
          <button
            onClick={() => setActiveTab("preferences")}
            className={activeTab === "preferences" ? "primary-btn" : "secondary-btn"}
            style={{ width: "auto" }}
          >
            User Preferences
          </button>
        )}
        {isAdminOrManager && (
          <button
            onClick={() => setActiveTab("types")}
            className={activeTab === "types" ? "primary-btn" : "secondary-btn"}
            style={{ width: "auto" }}
          >
            Shift Types
          </button>
        )}
      </div>

      {activeTab === "calendar" && (
        <div className="card" style={{ padding: 0, overflow: "hidden" }}>
          <div
            style={{
              padding: "1.5rem",
              background: "#f8fafc",
              borderBottom: "1px solid #e2e8f0",
              display: "flex",
              justifyContent: "space-between",
              flexWrap: "wrap",
              gap: "1rem",
            }}
          >
            <div style={{ display: "flex", gap: "0.75rem", alignItems: "center", flexWrap: "wrap" }}>
              <select
                value={calMonth}
                onChange={(e) => setCalMonth(parseInt(e.target.value, 10))}
                style={{ padding: "0.5rem", borderRadius: 4, border: "1px solid #cbd5e1" }}
              >
                {Array.from({ length: 12 }).map((_, i) => (
                  <option key={i} value={i}>
                    {new Date(2000, i).toLocaleString("default", { month: "long" })}
                  </option>
                ))}
              </select>
              <select
                value={calYear}
                onChange={(e) => setCalYear(parseInt(e.target.value, 10))}
                style={{ padding: "0.5rem", borderRadius: 4, border: "1px solid #cbd5e1" }}
              >
                <option value={new Date().getFullYear()}>{new Date().getFullYear()}</option>
                <option value={new Date().getFullYear() + 1}>{new Date().getFullYear() + 1}</option>
              </select>
              <select
                value={calDepartment}
                onChange={(e) => setCalDepartment(e.target.value)}
                style={{ padding: "0.5rem", borderRadius: 4, border: "1px solid #cbd5e1" }}
              >
                <option value="">All Departments</option>
                {departments.map((d) => (
                  <option key={d.id} value={d.id}>
                    {d.name} ({d.schedulePola || "POLA_1"})
                  </option>
                ))}
              </select>
              <select
                value={calLocation}
                onChange={(e) => setCalLocation(e.target.value)}
                style={{ padding: "0.5rem", borderRadius: 4, border: "1px solid #cbd5e1" }}
              >
                <option value="">All Locations</option>
                {locations.map((loc) => (
                  <option key={loc.id} value={loc.id}>
                    {loc.city}
                  </option>
                ))}
              </select>
              {isAdminOrManager && (
                <select
                  value={genPola}
                  onChange={(e) => setGenPola(e.target.value)}
                  style={{ padding: "0.5rem", borderRadius: 4, border: "1px solid #cbd5e1" }}
                  title="Override pola for this run (blank = department default)"
                >
                  <option value="">Pola: dept default</option>
                  {SCHEDULE_POLAS.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.label}
                    </option>
                  ))}
                </select>
              )}
            </div>
            {isAdminOrManager && (
              <button
                onClick={handleGenerate}
                disabled={generating}
                className="primary-btn"
                style={{ width: "auto", background: "#0f766e" }}
              >
                {generating ? "Generating…" : "Generate POLA Roster"}
              </button>
            )}
          </div>

          <div style={{ overflowX: "auto", padding: "1.5rem" }}>
            {loadingCal ? (
              <p>Loading Schedule Matrix...</p>
            ) : (
              <table
                style={{
                  width: "100%",
                  borderCollapse: "collapse",
                  textAlign: "center",
                  minWidth: 1200,
                }}
              >
                <thead>
                  <tr>
                    <th
                      style={{
                        padding: "0.75rem",
                        background: "#e2e8f0",
                        border: "1px solid #cbd5e1",
                        textAlign: "left",
                        position: "sticky",
                        left: 0,
                        zIndex: 1,
                      }}
                    >
                      Employee / Team
                    </th>
                    {dayHeaders.map((d) => {
                      const dateObj = new Date(calYear, calMonth, d);
                      const isWeekend = dateObj.getDay() === 0 || dateObj.getDay() === 6;
                      return (
                        <th
                          key={d}
                          style={{
                            padding: "0.5rem",
                            background: isWeekend ? "#fecaca" : "#f1f5f9",
                            border: "1px solid #cbd5e1",
                            fontSize: "0.8rem",
                            minWidth: 40,
                          }}
                        >
                          <div>{d}</div>
                          <div style={{ fontSize: "0.65rem", color: "#64748b" }}>
                            {dateObj.toLocaleDateString("en-US", { weekday: "short" })}
                          </div>
                        </th>
                      );
                    })}
                  </tr>
                </thead>
                <tbody>
                  {Object.values(gridData).map((row) => (
                    <tr key={row.user.id}>
                      <td
                        style={{
                          padding: "0.75rem",
                          border: "1px solid var(--border-color)",
                          textAlign: "left",
                          fontWeight: "bold",
                          background: "var(--table-header-bg)",
                          position: "sticky",
                          left: 0,
                        }}
                      >
                        {row.user.name || row.user.email}
                        <br />
                        <span style={{ fontSize: "0.7rem", color: "#64748b", fontWeight: "normal" }}>
                          {row.user.location?.city || "No Location"}
                        </span>
                      </td>
                      {dayHeaders.map((d) => {
                        const shift = row.days[d];
                        const isOff = Object.prototype.hasOwnProperty.call(row.days, d) && shift === null;
                        const isPending = !Object.prototype.hasOwnProperty.call(row.days, d);
                        return (
                          <td
                            key={d}
                            style={{
                              padding: "0.5rem",
                              border: "1px solid #cbd5e1",
                              fontSize: "0.75rem",
                              background: isOff ? "#f8fafc" : isPending ? "white" : "#dbeafe",
                            }}
                          >
                            {isOff ? (
                              <span style={{ color: "#94a3b8" }}>OFF</span>
                            ) : isPending ? (
                              <span style={{ color: "#cbd5e1" }}>-</span>
                            ) : (
                              <div style={{ fontWeight: "bold", color: "#1e40af" }}>{shift?.name}</div>
                            )}
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                  {Object.keys(gridData).length === 0 && (
                    <tr>
                      <td colSpan={daysInMonth + 1} style={{ padding: "2rem", color: "#94a3b8" }}>
                        No schedules generated for this range.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            )}
          </div>
        </div>
      )}

      {activeTab === "pola" && isAdminOrManager && (
        <div style={{ display: "grid", gap: "1.5rem" }}>
          <div className="card">
            <h2 style={{ marginTop: 0 }}>Default Pola per Departemen</h2>
            <p style={{ color: "#64748b" }}>
              Engine OR-Tools (adopsi sistem absen). Auto-generate tanggal {autoDay} memakai default ini
              untuk <strong>bulan berikutnya</strong>.
            </p>
            <table className="table" style={{ width: "100%", borderCollapse: "collapse" }}>
              <thead>
                <tr style={{ background: "#f1f5f9" }}>
                  <th style={{ padding: "0.75rem", textAlign: "left" }}>Department</th>
                  <th style={{ padding: "0.75rem", textAlign: "left" }}>Default Pola</th>
                </tr>
              </thead>
              <tbody>
                {departments.map((d) => (
                  <tr key={d.id} style={{ borderBottom: "1px solid #e2e8f0" }}>
                    <td style={{ padding: "0.75rem", fontWeight: 600 }}>{d.name}</td>
                    <td style={{ padding: "0.75rem" }}>
                      <select
                        value={d.schedulePola || "POLA_1"}
                        onChange={(e) => saveDeptPola(d.id, e.target.value)}
                        style={{ padding: "0.5rem", minWidth: 280 }}
                      >
                        {SCHEDULE_POLAS.map((p) => (
                          <option key={p.id} value={p.id}>
                            {p.label}
                          </option>
                        ))}
                      </select>
                    </td>
                  </tr>
                ))}
                {departments.length === 0 && (
                  <tr>
                    <td colSpan={2} style={{ padding: "1rem", color: "#94a3b8" }}>
                      Belum ada department.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
            <div style={{ marginTop: "1rem", fontSize: "0.85rem", color: "#64748b" }}>
              {SCHEDULE_POLAS.map((p) => (
                <div key={p.id} style={{ marginBottom: 4 }}>
                  <strong>{p.id}</strong> — {p.summary}
                </div>
              ))}
            </div>
          </div>

          <div className="card">
            <h2 style={{ marginTop: 0 }}>Auto-Generate</h2>
            <p style={{ color: "#64748b" }}>
              Setiap tanggal yang dikonfigurasi, sistem generate roster <strong>bulan depan</strong> untuk
              semua departemen (pola default masing-masing). Last run key:{" "}
              <code>{lastKey || "—"}</code>
            </p>
            <label style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: "0.75rem" }}>
              <input
                type="checkbox"
                checked={autoEnabled}
                onChange={(e) => setAutoEnabled(e.target.checked)}
              />
              Enable auto-generate
            </label>
            <label style={{ display: "block", marginBottom: "0.75rem" }}>
              Tanggal tiap bulan{" "}
              <input
                type="number"
                min={1}
                max={28}
                value={autoDay}
                onChange={(e) => setAutoDay(e.target.value)}
                style={{ width: 64, padding: "0.4rem", marginLeft: 8 }}
              />
            </label>
            <div style={{ display: "flex", gap: "0.75rem", flexWrap: "wrap" }}>
              <button type="button" className="primary-btn" style={{ width: "auto" }} onClick={saveAutoConfig}>
                Save settings
              </button>
              <button
                type="button"
                className="secondary-btn"
                style={{ width: "auto" }}
                onClick={forceAutoGenerate}
              >
                Force run now (next month)
              </button>
            </div>
          </div>
        </div>
      )}

      {activeTab === "preferences" && isAdminOrManager && (
        <div className="card">
          <h2 style={{ marginTop: 0 }}>Team Roster Preferences</h2>
          <p style={{ color: "#64748b", marginBottom: "1.5rem" }}>
            Flag (Umum/Kristen/Kuliah) dipakai constraint POLA. Mode FIXED/RANDOM hanya untuk legacy
            generator.
          </p>
          <table className="table" style={{ width: "100%", textAlign: "left", borderCollapse: "collapse" }}>
            <thead>
              <tr style={{ background: "#f1f5f9" }}>
                <th style={{ padding: "1rem" }}>User</th>
                <th style={{ padding: "1rem" }}>Flag</th>
                <th style={{ padding: "1rem" }}>Mode</th>
                <th style={{ padding: "1rem" }}>Fixed Shift</th>
                <th style={{ padding: "1rem" }}>Fixed Off-Days</th>
                <th style={{ padding: "1rem" }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {users.map((u) => {
                const pref = u.schedulePreference || {
                  scheduleMode: "RANDOM",
                  fixedOffDays: "[]",
                  fixedShiftId: null,
                };
                let offDays = [];
                try {
                  offDays = JSON.parse(pref.fixedOffDays);
                } catch {
                  /* ignore */
                }
                const isEditing = editPrefId === u.id;
                const daysOfWeek = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
                return (
                  <tr key={u.id} style={{ borderBottom: "1px solid #e2e8f0" }}>
                    <td style={{ padding: "1rem", fontWeight: "bold" }}>{u.name || u.email}</td>
                    {isEditing ? (
                      <>
                        <td style={{ padding: "1rem" }}>
                          <select
                            value={prefFormData.scheduleFlag || "Umum"}
                            onChange={(e) =>
                              setPrefFormData({ ...prefFormData, scheduleFlag: e.target.value })
                            }
                          >
                            {SCHEDULE_FLAGS.map((f) => (
                              <option key={f} value={f}>
                                {f}
                              </option>
                            ))}
                          </select>
                        </td>
                        <td style={{ padding: "1rem" }}>
                          <select
                            value={prefFormData.scheduleMode}
                            onChange={(e) =>
                              setPrefFormData({ ...prefFormData, scheduleMode: e.target.value })
                            }
                          >
                            <option value="RANDOM">Random Fill</option>
                            <option value="ROTATING">Rotating</option>
                            <option value="FIXED">Fixed</option>
                          </select>
                        </td>
                        <td style={{ padding: "1rem" }}>
                          <select
                            disabled={prefFormData.scheduleMode !== "FIXED"}
                            value={prefFormData.fixedShiftId || ""}
                            onChange={(e) =>
                              setPrefFormData({ ...prefFormData, fixedShiftId: e.target.value })
                            }
                          >
                            <option value="">--</option>
                            {shiftTypes.map((st) => (
                              <option key={st.id} value={st.id}>
                                {st.name}
                              </option>
                            ))}
                          </select>
                        </td>
                        <td style={{ padding: "1rem", fontSize: "0.8rem" }}>
                          <div style={{ display: "flex", gap: "0.2rem", flexWrap: "wrap" }}>
                            {daysOfWeek.map((dayName, idx) => (
                              <label
                                key={idx}
                                style={{
                                  background: prefFormData.fixedOffDays?.includes(idx)
                                    ? "#fca5a5"
                                    : "#f1f5f9",
                                  padding: "0.2rem 0.4rem",
                                  borderRadius: 4,
                                  cursor: "pointer",
                                }}
                              >
                                <input
                                  type="checkbox"
                                  style={{ display: "none" }}
                                  checked={prefFormData.fixedOffDays?.includes(idx)}
                                  onChange={() => toggleOffDay(idx)}
                                />
                                {dayName}
                              </label>
                            ))}
                          </div>
                        </td>
                        <td style={{ padding: "1rem" }}>
                          <button
                            onClick={() => handleSavePreference(u.id)}
                            className="primary-btn"
                            style={{ width: "auto", padding: "0.4rem 0.8rem", marginRight: "0.5rem" }}
                          >
                            Save
                          </button>
                          <button
                            onClick={() => setEditPrefId(null)}
                            className="secondary-btn"
                            style={{ width: "auto", padding: "0.4rem 0.8rem" }}
                          >
                            Cancel
                          </button>
                        </td>
                      </>
                    ) : (
                      <>
                        <td style={{ padding: "1rem" }}>{u.scheduleFlag || "Umum"}</td>
                        <td style={{ padding: "1rem" }}>
                          <span className="badge">{pref.scheduleMode}</span>
                        </td>
                        <td style={{ padding: "1rem", color: "#64748b" }}>
                          {pref.scheduleMode === "FIXED" && pref.fixedShift ? pref.fixedShift.name : "-"}
                        </td>
                        <td style={{ padding: "1rem", fontSize: "0.8rem" }}>
                          {offDays.length > 0 ? offDays.map((d) => daysOfWeek[d]).join(", ") : "None"}
                        </td>
                        <td style={{ padding: "1rem" }}>
                          <button
                            onClick={() => {
                              setPrefFormData({
                                scheduleMode: pref.scheduleMode,
                                fixedShiftId: pref.fixedShiftId,
                                fixedOffDays: offDays,
                                scheduleFlag: u.scheduleFlag || "Umum",
                              });
                              setEditPrefId(u.id);
                            }}
                            style={{
                              padding: "0.4rem 0.8rem",
                              background: "#e2e8f0",
                              border: "none",
                              borderRadius: 4,
                              cursor: "pointer",
                            }}
                          >
                            Config
                          </button>
                        </td>
                      </>
                    )}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {activeTab === "types" && isAdminOrManager && (
        <div className="card" style={{ maxWidth: 600 }}>
          <h2 style={{ marginTop: 0 }}>Shift Types</h2>
          <p style={{ color: "#64748b", fontSize: "0.9rem" }}>
            POLA engine memakai nama S1 / S2 / S3 / S1+OC (di-seed otomatis saat generate).
          </p>
          <form
            onSubmit={async (e) => {
              e.preventDefault();
              const res = await fetch("/api/schedules/types", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(shiftFormData),
              });
              if (res.ok) {
                setShiftTypes([...shiftTypes, await res.json()]);
                setShiftFormData({ name: "", startTime: "", endTime: "" });
              }
            }}
            style={{ display: "flex", gap: "1rem", marginBottom: "2rem", alignItems: "flex-end" }}
          >
            <div style={{ flex: 1 }}>
              <label style={{ display: "block", fontSize: "0.8rem", fontWeight: "bold" }}>Name</label>
              <input
                type="text"
                required
                value={shiftFormData.name}
                onChange={(e) => setShiftFormData({ ...shiftFormData, name: e.target.value })}
                style={{ width: "100%", padding: "0.5rem" }}
              />
            </div>
            <div>
              <label style={{ display: "block", fontSize: "0.8rem", fontWeight: "bold" }}>Start</label>
              <input
                type="time"
                required
                value={shiftFormData.startTime}
                onChange={(e) => setShiftFormData({ ...shiftFormData, startTime: e.target.value })}
                style={{ padding: "0.5rem" }}
              />
            </div>
            <div>
              <label style={{ display: "block", fontSize: "0.8rem", fontWeight: "bold" }}>End</label>
              <input
                type="time"
                required
                value={shiftFormData.endTime}
                onChange={(e) => setShiftFormData({ ...shiftFormData, endTime: e.target.value })}
                style={{ padding: "0.5rem" }}
              />
            </div>
            <button type="submit" className="primary-btn" style={{ width: "auto", padding: "0.6rem 1rem" }}>
              Add
            </button>
          </form>
          <ul style={{ listStyle: "none", padding: 0 }}>
            {shiftTypes.map((st) => (
              <li
                key={st.id}
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  padding: "1rem",
                  border: "1px solid #e2e8f0",
                  marginBottom: "0.5rem",
                  borderRadius: 4,
                  background: "#f8fafc",
                }}
              >
                <strong>{st.name}</strong>
                <span style={{ color: "#64748b" }}>
                  {st.startTime} to {st.endTime}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
