import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "../../auth/[...nextauth]/route";
import { getAppConfig, updateAppConfig } from "@/lib/config";

async function requireScheduleAdmin(session) {
  return (
    session?.user?.role === "Admin" ||
    session?.user?.permissions?.includes("manage_schedules") ||
    session?.user?.permissions?.includes("manage_settings")
  );
}

export async function GET() {
  const session = await getServerSession(authOptions);
  if (!(await requireScheduleAdmin(session))) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }
  const config = await getAppConfig();
  return NextResponse.json({
    scheduleAutoGenerateEnabled: config.scheduleAutoGenerateEnabled !== false,
    scheduleAutoGenerateDay: config.scheduleAutoGenerateDay ?? 15,
    scheduleAutoGenerateHour: config.scheduleAutoGenerateHour ?? 1,
    lastScheduleAutoGenerateKey: config.lastScheduleAutoGenerateKey || "",
  });
}

export async function POST(req) {
  const session = await getServerSession(authOptions);
  if (!(await requireScheduleAdmin(session))) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }
  const body = await req.json().catch(() => ({}));
  const patch = {};
  if (body.scheduleAutoGenerateEnabled != null) {
    patch.scheduleAutoGenerateEnabled = !!body.scheduleAutoGenerateEnabled;
  }
  if (body.scheduleAutoGenerateDay != null) {
    const day = parseInt(body.scheduleAutoGenerateDay, 10);
    if (day < 1 || day > 28) {
      return NextResponse.json({ error: "day must be 1–28" }, { status: 400 });
    }
    patch.scheduleAutoGenerateDay = day;
  }
  if (body.scheduleAutoGenerateHour != null) {
    patch.scheduleAutoGenerateHour = parseInt(body.scheduleAutoGenerateHour, 10);
  }
  const updated = await updateAppConfig(patch);
  return NextResponse.json({
    scheduleAutoGenerateEnabled: updated.scheduleAutoGenerateEnabled !== false,
    scheduleAutoGenerateDay: updated.scheduleAutoGenerateDay ?? 15,
    scheduleAutoGenerateHour: updated.scheduleAutoGenerateHour ?? 1,
    lastScheduleAutoGenerateKey: updated.lastScheduleAutoGenerateKey || "",
  });
}
