/**
 * Lightweight hourly checker: on scheduleAutoGenerateDay at scheduleAutoGenerateHour,
 * POST /api/schedules/auto-generate (generates next month via pola engine).
 *
 * Env:
 *  - APP_INTERNAL_URL (default http://127.0.0.1:3000)
 *  - SCHEDULE_CRON_SECRET
 */
const APP_URL = (process.env.APP_INTERNAL_URL || "http://127.0.0.1:3000").replace(
  /\/$/,
  ""
);
const SECRET = process.env.SCHEDULE_CRON_SECRET || process.env.CRON_SECRET || "";

async function tick() {
  try {
    const res = await fetch(`${APP_URL}/api/schedules/auto-generate`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(SECRET ? { "x-cron-secret": SECRET } : {}),
      },
      body: JSON.stringify({}),
    });
    const text = await res.text();
    console.log(`[schedule-cron] ${new Date().toISOString()} ${res.status} ${text.slice(0, 300)}`);
  } catch (err) {
    console.error("[schedule-cron]", err.message);
  }
}

console.log(`[schedule-cron] started → ${APP_URL} (hourly)`);
tick();
setInterval(tick, 60 * 60 * 1000);
