import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "../../auth/[...nextauth]/route";
import { getAppConfig, updateAppConfig } from "@/lib/config";
import {
  generateAllDepartmentsMonth,
  nextMonthPartsJakarta,
} from "@/lib/schedules/generatePola";
import { nowInJakarta } from "@/lib/schedules/dates";

function authorized(req, session) {
  const secret = process.env.SCHEDULE_CRON_SECRET || process.env.CRON_SECRET;
  const header = req.headers.get("x-cron-secret");
  if (secret && header && header === secret) return true;
  return (
    session?.user?.role === "Admin" ||
    session?.user?.permissions?.includes("manage_schedules")
  );
}

/**
 * POST /api/schedules/auto-generate
 * Day/hour evaluated in Asia/Jakarta. lastKey only saved when no hard failures.
 */
export async function POST(req) {
  try {
    const session = await getServerSession(authOptions);
    if (!authorized(req, session)) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const body = await req.json().catch(() => ({}));
    const config = await getAppConfig();
    const force = !!body.force;
    const day = parseInt(config.scheduleAutoGenerateDay ?? 15, 10);
    const jakarta = nowInJakarta();

    if (!force) {
      if (config.scheduleAutoGenerateEnabled === false) {
        return NextResponse.json({ skipped: true, reason: "disabled", tz: "Asia/Jakarta" });
      }
      if (jakarta.day !== day) {
        return NextResponse.json({
          skipped: true,
          reason: `Jakarta day is ${jakarta.day}, configured day is ${day}`,
          jakarta,
        });
      }
      const hour = parseInt(config.scheduleAutoGenerateHour ?? 1, 10);
      if (jakarta.hour !== hour) {
        return NextResponse.json({
          skipped: true,
          reason: `Jakarta hour is ${jakarta.hour}, configured hour is ${hour}`,
          jakarta,
        });
      }
    }

    const target =
      body.year && body.month
        ? { year: parseInt(body.year, 10), month: parseInt(body.month, 10) }
        : nextMonthPartsJakarta();

    const key = `${target.year}-${String(target.month).padStart(2, "0")}`;
    if (!force && config.lastScheduleAutoGenerateKey === key) {
      return NextResponse.json({ skipped: true, reason: "already generated", key });
    }

    const results = await generateAllDepartmentsMonth({
      year: target.year,
      month: target.month,
    });

    const hardFails = results.filter((r) => r.ok === false);
    const recorded = hardFails.length === 0;
    if (recorded) {
      await updateAppConfig({ lastScheduleAutoGenerateKey: key });
    }

    return NextResponse.json({
      success: recorded,
      partial: hardFails.length > 0 && results.some((r) => r.ok),
      recordedLastKey: recorded,
      target,
      key,
      jakarta,
      results,
      ...(hardFails.length
        ? { warning: "lastKey not saved — fix failures and retry (or force)" }
        : {}),
    });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function GET(req) {
  const session = await getServerSession(authOptions);
  if (!authorized(req, session)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }
  const config = await getAppConfig();
  return NextResponse.json({
    enabled: config.scheduleAutoGenerateEnabled !== false,
    day: config.scheduleAutoGenerateDay ?? 15,
    hour: config.scheduleAutoGenerateHour ?? 1,
    lastKey: config.lastScheduleAutoGenerateKey || null,
    nextTarget: nextMonthPartsJakarta(),
    jakarta: nowInJakarta(),
    tz: "Asia/Jakarta",
  });
}
