import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "../../auth/[...nextauth]/route";
import { getAppConfig, updateAppConfig } from "@/lib/config";
import {
  generateAllDepartmentsMonth,
  nextMonthParts,
} from "@/lib/schedules/generatePola";

function authorized(req, session) {
  const secret = process.env.SCHEDULE_CRON_SECRET || process.env.CRON_SECRET;
  const header = req.headers.get("x-cron-secret");
  if (secret && header && header === secret) return true;
  return (
    session?.user?.role === "Admin" ||
    session?.user?.permissions?.includes("manage_schedules")
  );
}

/**
 * POST /api/schedules/auto-generate
 * Runs pola generate for next month (default) if today matches configured day,
 * or force=true to run immediately.
 */
export async function POST(req) {
  try {
    const session = await getServerSession(authOptions);
    if (!authorized(req, session)) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const body = await req.json().catch(() => ({}));
    const config = await getAppConfig();
    const force = !!body.force;
    const day = parseInt(config.scheduleAutoGenerateDay ?? 15, 10);
    const now = new Date();

    if (!force) {
      if (config.scheduleAutoGenerateEnabled === false) {
        return NextResponse.json({ skipped: true, reason: "disabled" });
      }
      if (now.getDate() !== day) {
        return NextResponse.json({
          skipped: true,
          reason: `today is ${now.getDate()}, configured day is ${day}`,
        });
      }
      const hour = parseInt(config.scheduleAutoGenerateHour ?? 1, 10);
      if (now.getHours() !== hour) {
        return NextResponse.json({
          skipped: true,
          reason: `hour is ${now.getHours()}, configured hour is ${hour}`,
        });
      }
    }

    const target = body.year && body.month
      ? { year: parseInt(body.year, 10), month: parseInt(body.month, 10) }
      : nextMonthParts(now);

    const key = `${target.year}-${String(target.month).padStart(2, "0")}`;
    if (!force && config.lastScheduleAutoGenerateKey === key) {
      return NextResponse.json({ skipped: true, reason: "already generated", key });
    }

    const results = await generateAllDepartmentsMonth({
      year: target.year,
      month: target.month,
    });

    await updateAppConfig({ lastScheduleAutoGenerateKey: key });

    return NextResponse.json({
      success: true,
      target,
      key,
      results,
    });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function GET(req) {
  const session = await getServerSession(authOptions);
  if (!authorized(req, session)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }
  const config = await getAppConfig();
  return NextResponse.json({
    enabled: config.scheduleAutoGenerateEnabled !== false,
    day: config.scheduleAutoGenerateDay ?? 15,
    hour: config.scheduleAutoGenerateHour ?? 1,
    lastKey: config.lastScheduleAutoGenerateKey || null,
    nextTarget: nextMonthParts(new Date()),
  });
}
